##### NumPy Arrays

In [1]:
# Homogeneous: must have same datatype elements
# multidimentional

import numpy as np



In [2]:
array_1d = np.array([2,3,4,5,6,7])
print(array_1d)
print(type(array_1d))

[2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [4]:
array_2d = np.array([[2,3,4], [5,6,7]])
print(array_2d)
print(type(array_2d))

[[2 3 4]
 [5 6 7]]
<class 'numpy.ndarray'>


In numppy, dimentions are called as Axes. In 2-d array, have 2 * 3

axis = 0 means rows
axis = 1 means columns

Advantages of NumPy
What is the use of arrays over lists, specifically for data analysis? Putting crudely, it is convenience and speed :

1. You can write vectorised code on NumPy arrays, not on lists, which is convenient to read and write, and concise.
2. NumPy is much faster than the standard Python ways to do computations.<br>
Vectorised code typically does not contain explicit looping and indexing etc. (all of this happens behind the scenes, in precompiled C-code), and thus it is much more concise.

 

In [7]:
# Lists are different than NumPy array
list_1 = [2, 3, 4, 5]
list_2 = [6, 7, 8, 9]

prod = list(map(lambda x,y : x*y, list_1, list_2))
print(prod)

[12, 21, 32, 45]


In [8]:
#Element Wise Multiplication in Numpy

np_list_1 = np.array([2, 3, 4, 5])
np_list_2 = np.array([6, 7, 8, 9])

prod = np_list_1 * np_list_2
print(prod)

[12 21 32 45]


In [10]:
# Square

square = list(map(lambda x : x**2, range(1,6)))
print(square)

[1, 4, 9, 16, 25]


In [11]:
num = np.array(range(1,6))
print(num ** 2)


[ 1  4  9 16 25]



##### Creating NumPy Arrays

In [12]:
array_from_list = np.array([2,3,4,5])
print(array_from_list)

[2 3 4 5]


The following ways are commonly used:

np.ones(): Create an array of 1s <br>
np.zeros(): Create an array of 0s <br>
np.random.random(): Create an array of random numbers between 0 and 1 <br>
np.arange(): Create an array with increments of a fixed step size <br>
np.linspace(): Create an array of fixed length <br>
np.full(): Create a constant array of any number ‘n’ <br>
np.tile(): Create a new array — by repeating an existing array — for a particular number of times <br>
np.eye(): Create an identity matrix of any dimension <br>
np.randint(): Create a random array of integers within a particular range <br>

In [16]:
# creating 5 *3 dimentional array
np.ones((5 , 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.ones((5 , 3), dtype = np.int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
np.zeros((5), dtype = np.int)

array([0, 0, 0, 0, 0])

In [24]:
np.random.random([2,5])

array([[0.67595823, 0.60751354, 0.1350682 , 0.56275046, 0.39624577],
       [0.15764896, 0.98686985, 0.7452768 , 0.5466214 , 0.66555284]])

In [26]:
np.arange(10, 100)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [27]:
np.arange(10, 100, 10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [31]:
np.linspace(10, 15, 5)

array([10.  , 11.25, 12.5 , 13.75, 15.  ])

In [36]:
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [39]:
np.tile([1, 2], 5)

array([1, 2, 1, 2, 1, 2, 1, 2, 1, 2])

In [41]:
np.eye(2*2)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
np.random.randint(10, size =(1,10))

array([[8, 6, 8, 8, 0, 8, 6, 4, 1, 3]])

In [57]:
#Checkboard Array using tile function

n= 6
arr = ([0, 1], [1, 0] )
print(np.tile(arr, (n//2, n//2)))

##### Structure and Content of Arrays

In [60]:
rand_array = np.random.random((100,1000))

In [64]:
print(rand_array[0:])

[[0.65424162 0.99623091 0.76705133 ... 0.81102845 0.82247237 0.65268978]
 [0.20481449 0.06656813 0.7655517  ... 0.62978323 0.00996929 0.27646512]
 [0.12378863 0.271794   0.0158988  ... 0.42085951 0.2364305  0.64697201]
 ...
 [0.18957873 0.54007363 0.58731389 ... 0.23172573 0.80124291 0.99868762]
 [0.91197363 0.22292119 0.56744411 ... 0.45309119 0.14825531 0.04303838]
 [0.66770745 0.52054389 0.02679892 ... 0.38347665 0.18371044 0.78828765]]


In [70]:
np.shape(rand_array)


(100, 1000)

In [74]:
print(rand_array.dtype)

float64


In [75]:
np.ndim(rand_array)

2

In [77]:
print(rand_array.itemsize)

8


In [78]:
array_3d = np.arange(24).reshape(2, 3 ,4)
print(array_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


##### Subset, Slice, Index and Iterate through Arrays

In [79]:
array_1d = np.arange(10)
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


In [80]:
print(array_1d[2])

2


In [81]:
print(array_1d[[2,5,6]])

[2 5 6]


In [82]:
print(array_1d[:])

[0 1 2 3 4 5 6 7 8 9]


In [90]:
print(array_1d[0::2])

[0 2 4 6 8]


In [88]:
#Not Recommended
for i in array_1d:
    print(i)

0
1
2
3
4
5
6
7
8
9


##### Multi Dimentional Array

In [94]:
array_2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [100]:
print(array_2d[2,1:])

[8 9]


In [101]:
print(array_2d[2,:])

[7 8 9]


In [103]:
print(array_2d[2,:-1])

[7 8]


In [105]:
print(array_2d[:,:2])

[[1 2]
 [4 5]
 [7 8]]


In [106]:
print(array_2d[:,2])

[3 6 9]


In [107]:
#Iteration
for row in array_2d:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [108]:
array_3d = np.arange(24).reshape(2,3,4)
print(array_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [112]:
for row in array_3d:
    print(row)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


##### Resource
https://numpy.org/